n = input('digite algo: ')
print(n , 'é numérico: ', n.isnumeric())
print(n , 'é tipo:', type(n))
print(n , ' é alpha?', n.isalpha())
print(n , 'é decimal?', n.isdecimal())
print(n, 'é printável?', n.isprintable())
print(n, 'é printável?', n.isalnum())